# -*- coding: utf-8 -*-
"""Kukapickandplace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kWH9_gmwPJhF3RPKcsuiGPoiIbEyVWs
"""

!pip install pybullet

import pybullet as p
import pybullet_data
import matplotlib.pyplot as plt
import numpy as np

# Reset and connect
p.connect(p.DIRECT)
p.resetSimulation()

# Basic setup
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81)

# Ground
p.loadURDF("plane.urdf")

# 5 feet in meters
spacing = 1.524

# Use a UR-style arm available in pybullet_data
# If one URDF path fails, try the fallback below
robot_paths = [
    "ur5/ur5.urdf",
    "kuka_iiwa/model.urdf",   # fallback if UR5 is unavailable
]

robot_path = None
for path in robot_paths:
    try:
        p.loadURDF(path, [100, 100, 100])  # quick test load offscreen
        robot_path = path
        p.resetSimulation()
        p.setAdditionalSearchPath(pybullet_data.getDataPath())
        p.setGravity(0, 0, -9.81)
        p.loadURDF("plane.urdf")
        break
    except:
        pass

if robot_path is None:
    raise FileNotFoundError("Could not find a UR robot URDF in pybullet_data.")

# Robot base positions: three arms side by side
robot_positions = [
    [-spacing, 0, 0],
    [0, 0, 0],
    [spacing, 0, 0],
]

robots = []
for pos in robot_positions:
    robot_id = p.loadURDF(
        robot_path,
        basePosition=pos,
        baseOrientation=p.getQuaternionFromEuler([0, 0, 0]),
        useFixedBase=True
    )
    robots.append(robot_id)

# Create one block in front of each robot
block_ids = []
block_positions = [
    [-spacing, 0.7, 0.05],
    [0, 0.7, 0.05],
    [spacing, 0.7, 0.05],
]

for pos in block_positions:
    block_id = p.loadURDF("cube_small.urdf", basePosition=pos)
    block_ids.append(block_id)

# Let the scene settle
for _ in range(200):
    p.stepSimulation()

# Camera setup
view_matrix = p.computeViewMatrixFromYawPitchRoll(
    cameraTargetPosition=[0, 0.5, 0.3],
    distance=4.5,
    yaw=45,
    pitch=-30,
    roll=0,
    upAxisIndex=2
)

projection_matrix = p.computeProjectionMatrixFOV(
    fov=60,
    aspect=640 / 480,
    nearVal=0.1,
    farVal=100
)

width, height, rgb_img, depth_img, seg_img = p.getCameraImage(
    width=640,
    height=480,
    viewMatrix=view_matrix,
    projectionMatrix=projection_matrix,
    renderer=p.ER_TINY_RENDERER
)

rgb_array = np.reshape(rgb_img, (height, width, 4))[:, :, :3]

plt.figure(figsize=(10, 6))
plt.imshow(rgb_array)
plt.axis("off")
plt.show()

import pybullet as p
import pybullet_data
import matplotlib.pyplot as plt
import numpy as np
import time
import math

# ----------------------------
# Setup
# ----------------------------
p.connect(p.DIRECT)
p.resetSimulation()
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81)

plane_id = p.loadURDF("plane.urdf")

# 5 feet = 1.524 meters
spacing = 1.524

robot_path = "kuka_iiwa/model.urdf"

robot_positions = [
    [-spacing, 0.0, 0.0],
    [0.0,      0.0, 0.0],
    [spacing,  0.0, 0.0],
]

robots = []
for pos in robot_positions:
    robot_id = p.loadURDF(
        robot_path,
        basePosition=pos,
        baseOrientation=p.getQuaternionFromEuler([0, 0, 0]),
        useFixedBase=True
    )
    robots.append(robot_id)

# ----------------------------
# Helper functions
# ----------------------------
def get_revolute_joints(robot_id):
    joints = []
    for j in range(p.getNumJoints(robot_id)):
        info = p.getJointInfo(robot_id, j)
        joint_type = info[2]
        if joint_type == p.JOINT_REVOLUTE:
            joints.append(j)
    return joints

def reset_arm_pose(robot_id, joint_positions):
    revolute_joints = get_revolute_joints(robot_id)
    for j, q in zip(revolute_joints, joint_positions):
        p.resetJointState(robot_id, j, q)

def move_ee(robot_id, target_pos, steps=120):
    revolute_joints = get_revolute_joints(robot_id)
    ee_link = revolute_joints[-1]

    ik_solution = p.calculateInverseKinematics(robot_id, ee_link, target_pos)

    for _ in range(steps):
        for joint_index, joint_id in enumerate(revolute_joints):
            p.setJointMotorControl2(
                bodyIndex=robot_id,
                jointIndex=joint_id,
                controlMode=p.POSITION_CONTROL,
                targetPosition=ik_solution[joint_index],
                force=500
            )
        p.stepSimulation()

def create_colored_block(position, rgba, half_extents=(0.025, 0.025, 0.025), mass=0.1):
    collision = p.createCollisionShape(
        p.GEOM_BOX,
        halfExtents=half_extents
    )
    visual = p.createVisualShape(
        p.GEOM_BOX,
        halfExtents=half_extents,
        rgbaColor=rgba
    )
    block_id = p.createMultiBody(
        baseMass=mass,
        baseCollisionShapeIndex=collision,
        baseVisualShapeIndex=visual,
        basePosition=position
    )
    return block_id

def attach_block_to_ee(robot_id, block_id):
    revolute_joints = get_revolute_joints(robot_id)
    ee_link = revolute_joints[-1]

    ee_state = p.getLinkState(robot_id, ee_link)
    ee_pos = ee_state[0]

    # Snap block to end effector before attaching
    p.resetBasePositionAndOrientation(block_id, ee_pos, [0, 0, 0, 1])

    cid = p.createConstraint(
        parentBodyUniqueId=robot_id,
        parentLinkIndex=ee_link,
        childBodyUniqueId=block_id,
        childLinkIndex=-1,
        jointType=p.JOINT_FIXED,
        jointAxis=[0, 0, 0],
        parentFramePosition=[0, 0, 0],
        childFramePosition=[0, 0, 0]
    )
    return cid

def release_block(constraint_id):
    p.removeConstraint(constraint_id)

def pick_and_place(robot_id, block_id, pick_pos, place_pos):
    # approach above block
    above_pick = [pick_pos[0], pick_pos[1], pick_pos[2] + 0.22]
    touch_pick = [pick_pos[0], pick_pos[1], pick_pos[2] + 0.05]

    # approach above place
    above_place = [place_pos[0], place_pos[1], place_pos[2] + 0.22]
    touch_place = [place_pos[0], place_pos[1], place_pos[2] + 0.06]

    # move to block
    move_ee(robot_id, above_pick, steps=120)
    move_ee(robot_id, touch_pick, steps=120)

    # grab block
    constraint_id = attach_block_to_ee(robot_id, block_id)

    # lift
    move_ee(robot_id, above_pick, steps=120)

    # move to stack
    move_ee(robot_id, above_place, steps=160)
    move_ee(robot_id, touch_place, steps=120)

    # release
    release_block(constraint_id)

    # let physics settle
    for _ in range(60):
        p.stepSimulation()

    # retreat
    move_ee(robot_id, above_place, steps=100)

# ----------------------------
# Initial arm pose
# ----------------------------
home_q = [0, 0.4, 0, -1.6, 0, 1.2, 0]
for robot_id in robots:
    reset_arm_pose(robot_id, home_q)

for _ in range(100):
    p.stepSimulation()

# ----------------------------
# Create red, white, blue blocks
# One block in front of each robot
# ----------------------------
block_positions = [
    [-spacing, 0.75, 0.025],   # left robot block
    [0.0,      0.75, 0.025],   # middle robot block
    [spacing,  0.75, 0.025],   # right robot block
]

red_block = create_colored_block(block_positions[0], [1, 0, 0, 1])
white_block = create_colored_block(block_positions[1], [1, 1, 1, 1])
blue_block = create_colored_block(block_positions[2], [0, 0, 1, 1])

for _ in range(100):
    p.stepSimulation()

# ----------------------------
# Stack location in center
# cube height = 0.05
# ----------------------------
stack_x = 0.0
stack_y = 1.10

stack_positions = [
    [stack_x, stack_y, 0.025],  # bottom
    [stack_x, stack_y, 0.075],  # middle
    [stack_x, stack_y, 0.125],  # top
]

# ----------------------------
# Pick and stack:
# left arm places red at bottom
# middle arm places white in middle
# right arm places blue on top
# ----------------------------
pick_and_place(robots[0], red_block,   block_positions[0], stack_positions[0])
pick_and_place(robots[1], white_block, block_positions[1], stack_positions[1])
pick_and_place(robots[2], blue_block,  block_positions[2], stack_positions[2])

for _ in range(200):
    p.stepSimulation()

# ----------------------------
# Render final image
# ----------------------------
view_matrix = p.computeViewMatrixFromYawPitchRoll(
    cameraTargetPosition=[0.0, 0.8, 0.2],
    distance=5.0,
    yaw=45,
    pitch=-28,
    roll=0,
    upAxisIndex=2
)

projection_matrix = p.computeProjectionMatrixFOV(
    fov=60,
    aspect=640/480,
    nearVal=0.1,
    farVal=100
)

width, height, rgb_img, depth_img, seg_img = p.getCameraImage(
    width=640,
    height=480,
    viewMatrix=view_matrix,
    projectionMatrix=projection_matrix,
    renderer=p.ER_TINY_RENDERER
)

rgb_array = np.reshape(rgb_img, (height, width, 4))[:, :, :3]

plt.figure(figsize=(12, 7))
plt.imshow(rgb_array)
plt.axis("off")
plt.show()

!pip install pybullet imageio

import pybullet as p
import pybullet_data
import numpy as np
import matplotlib.pyplot as plt
import imageio
from IPython.display import Video

p.connect(p.DIRECT)
p.resetSimulation()
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81)

plane_id = p.loadURDF("plane.urdf")
p.changeVisualShape(plane_id, -1, rgbaColor=[0, 0, 0, 1])

spacing = 1.524
robot_path = "kuka_iiwa/model.urdf"

robot_positions = [
    [-spacing, 0.0, 0.0],
    [0.0,      0.0, 0.0],
    [spacing,  0.0, 0.0],
]

robots = []
for pos in robot_positions:
    robot_id = p.loadURDF(
        robot_path,
        basePosition=pos,
        baseOrientation=p.getQuaternionFromEuler([0, 0, 0]),
        useFixedBase=True
    )
    robots.append(robot_id)

CAM_W, CAM_H = 800, 500
frames = []

def get_rgb_frame():
    view_matrix = p.computeViewMatrixFromYawPitchRoll(
        cameraTargetPosition=[0.0, 0.9, 0.25],
        distance=5.3,
        yaw=45,
        pitch=-28,
        roll=0,
        upAxisIndex=2
    )
    projection_matrix = p.computeProjectionMatrixFOV(
        fov=60,
        aspect=CAM_W / CAM_H,
        nearVal=0.1,
        farVal=100
    )
    img = p.getCameraImage(
        width=CAM_W,
        height=CAM_H,
        viewMatrix=view_matrix,
        projectionMatrix=projection_matrix,
        renderer=p.ER_TINY_RENDERER
    )
    rgb = np.reshape(img[2], (CAM_H, CAM_W, 4))[:, :, :3]
    return rgb

def capture_frame():
    frames.append(get_rgb_frame())

def get_revolute_joints(robot_id):
    joints = []
    for j in range(p.getNumJoints(robot_id)):
        info = p.getJointInfo(robot_id, j)
        if info[2] == p.JOINT_REVOLUTE:
            joints.append(j)
    return joints

def reset_arm_pose(robot_id, joint_positions):
    joints = get_revolute_joints(robot_id)
    for j, q in zip(joints, joint_positions):
        p.resetJointState(robot_id, j, q)

def step_and_capture(num_steps, capture_every=4):
    for i in range(num_steps):
        p.stepSimulation()
        if i % capture_every == 0:
            capture_frame()

def move_ee(robot_id, target_pos, steps=100, capture_every=4):
    joints = get_revolute_joints(robot_id)
    ee_link = joints[-1]
    target_orn = p.getQuaternionFromEuler([0, np.pi, 0])
    ik_solution = p.calculateInverseKinematics(
        robot_id,
        ee_link,
        target_pos,
        targetOrientation=target_orn
    )

    for i in range(steps):
        for joint_index, joint_id in enumerate(joints):
            p.setJointMotorControl2(
                bodyIndex=robot_id,
                jointIndex=joint_id,
                controlMode=p.POSITION_CONTROL,
                targetPosition=ik_solution[joint_index],
                force=500
            )
        p.stepSimulation()
        if i % capture_every == 0:
            capture_frame()

def create_colored_block(position, rgba, half_extents=(0.03, 0.03, 0.03), mass=0.15):
    collision = p.createCollisionShape(
        p.GEOM_BOX,
        halfExtents=half_extents
    )
    visual = p.createVisualShape(
        p.GEOM_BOX,
        halfExtents=half_extents,
        rgbaColor=rgba
    )
    block_id = p.createMultiBody(
        baseMass=mass,
        baseCollisionShapeIndex=collision,
        baseVisualShapeIndex=visual,
        basePosition=position
    )
    return block_id

def attach_block_to_ee(robot_id, block_id):
    joints = get_revolute_joints(robot_id)
    ee_link = joints[-1]
    ee_state = p.getLinkState(robot_id, ee_link)
    ee_pos = ee_state[0]
    ee_orn = ee_state[1]

    p.resetBasePositionAndOrientation(block_id, ee_pos, ee_orn)

    cid = p.createConstraint(
        parentBodyUniqueId=robot_id,
        parentLinkIndex=ee_link,
        childBodyUniqueId=block_id,
        childLinkIndex=-1,
        jointType=p.JOINT_FIXED,
        jointAxis=[0, 0, 0],
        parentFramePosition=[0, 0, 0.08],
        childFramePosition=[0, 0, 0]
    )
    return cid

def release_block(cid):
    p.removeConstraint(cid)

def pick_and_place(robot_id, block_id, pick_pos, place_pos):
    above_pick  = [pick_pos[0],  pick_pos[1],  pick_pos[2]  + 0.30]
    grab_pick   = [pick_pos[0],  pick_pos[1],  pick_pos[2]  + 0.08]
    above_place = [place_pos[0], place_pos[1], place_pos[2] + 0.30]
    set_place   = [place_pos[0], place_pos[1], place_pos[2] + 0.08]

    move_ee(robot_id, above_pick,  steps=100, capture_every=4)
    move_ee(robot_id, grab_pick,   steps=100, capture_every=4)

    cid = attach_block_to_ee(robot_id, block_id)
    capture_frame()

    move_ee(robot_id, above_pick,  steps=100, capture_every=4)
    move_ee(robot_id, above_place, steps=140, capture_every=4)
    move_ee(robot_id, set_place,   steps=100, capture_every=4)

    release_block(cid)
    step_and_capture(50, capture_every=2)

    move_ee(robot_id, above_place, steps=100, capture_every=4)

home_q = [0, 0.4, 0, -1.6, 0, 1.2, 0]
for robot_id in robots:
    reset_arm_pose(robot_id, home_q)

step_and_capture(60, capture_every=4)

block_positions = [
    [-spacing, 0.78, 0.03],
    [0.0,      0.78, 0.03],
    [spacing,  0.78, 0.03],
]

red_block   = create_colored_block(block_positions[0], [1, 0, 0, 1])
white_block = create_colored_block(block_positions[1], [1, 1, 1, 1])
blue_block  = create_colored_block(block_positions[2], [0, 0, 1, 1])

platform_collision = p.createCollisionShape(
    p.GEOM_BOX,
    halfExtents=[0.10, 0.10, 0.02]
)
platform_visual = p.createVisualShape(
    p.GEOM_BOX,
    halfExtents=[0.10, 0.10, 0.02],
    rgbaColor=[0.4, 0.4, 0.4, 1]
)
platform_id = p.createMultiBody(
    baseMass=0,
    baseCollisionShapeIndex=platform_collision,
    baseVisualShapeIndex=platform_visual,
    basePosition=[0.0, 1.15, 0.02]
)

step_and_capture(60, capture_every=4)

stack_x = 0.0
stack_y = 1.15

stack_positions = [
    [stack_x, stack_y, 0.05],
    [stack_x, stack_y, 0.11],
    [stack_x, stack_y, 0.17],
]

pick_and_place(robots[0], red_block,   block_positions[0], stack_positions[0])
pick_and_place(robots[1], white_block, block_positions[1], stack_positions[1])
pick_and_place(robots[2], blue_block,  block_positions[2], stack_positions[2])

step_and_capture(100, capture_every=3)

video_path = "/content/stack_demo.mp4"
imageio.mimsave(video_path, frames, fps=20)

Video(video_path, embed=True)

import pybullet as p
import pybullet_data
import numpy as np
import imageio
from IPython.display import Video

# ----------------------------
# Setup
# ----------------------------
p.connect(p.DIRECT)
p.resetSimulation()
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.setGravity(0, 0, -9.81)

plane_id = p.loadURDF("plane.urdf")
p.changeVisualShape(plane_id, -1, rgbaColor=[0, 0, 0, 1])

spacing = 1.524  # 5 ft
robot_path = "kuka_iiwa/model.urdf"

robot_positions = [
    [-spacing, 0.0, 0.0],
    [0.0,      0.0, 0.0],
    [spacing,  0.0, 0.0],
]

robots = []
for pos in robot_positions:
    robot_id = p.loadURDF(
        robot_path,
        basePosition=pos,
        baseOrientation=p.getQuaternionFromEuler([0, 0, 0]),
        useFixedBase=True
    )
    robots.append(robot_id)

# ----------------------------
# Camera / video
# ----------------------------
CAM_W, CAM_H = 900, 520
frames = []

def get_rgb_frame():
    view_matrix = p.computeViewMatrixFromYawPitchRoll(
        cameraTargetPosition=[0.0, 1.1, 0.28],
        distance=6.4,
        yaw=45,
        pitch=-28,
        roll=0,
        upAxisIndex=2
    )
    projection_matrix = p.computeProjectionMatrixFOV(
        fov=60,
        aspect=CAM_W / CAM_H,
        nearVal=0.1,
        farVal=100
    )
    img = p.getCameraImage(
        width=CAM_W,
        height=CAM_H,
        viewMatrix=view_matrix,
        projectionMatrix=projection_matrix,
        renderer=p.ER_TINY_RENDERER
    )
    rgb = np.reshape(img[2], (CAM_H, CAM_W, 4))[:, :, :3]
    return rgb

def capture_frame():
    frames.append(get_rgb_frame())

# ----------------------------
# Robot helpers
# ----------------------------
def get_revolute_joints(robot_id):
    joints = []
    for j in range(p.getNumJoints(robot_id)):
        info = p.getJointInfo(robot_id, j)
        if info[2] == p.JOINT_REVOLUTE:
            joints.append(j)
    return joints

def reset_arm_pose(robot_id, joint_positions):
    joints = get_revolute_joints(robot_id)
    for j, q in zip(joints, joint_positions):
        p.resetJointState(robot_id, j, q)

def step_and_capture(num_steps, capture_every=4):
    for i in range(num_steps):
        p.stepSimulation()
        if i % capture_every == 0:
            capture_frame()

def move_ee(robot_id, target_pos, steps=100, capture_every=4):
    joints = get_revolute_joints(robot_id)
    ee_link = joints[-1]
    target_orn = p.getQuaternionFromEuler([0, np.pi, 0])

    ik_solution = p.calculateInverseKinematics(
        robot_id,
        ee_link,
        target_pos,
        targetOrientation=target_orn
    )

    for i in range(steps):
        for joint_index, joint_id in enumerate(joints):
            p.setJointMotorControl2(
                bodyIndex=robot_id,
                jointIndex=joint_id,
                controlMode=p.POSITION_CONTROL,
                targetPosition=ik_solution[joint_index],
                force=500
            )
        p.stepSimulation()
        if i % capture_every == 0:
            capture_frame()

def create_colored_block(position, rgba, half_extents=(0.03, 0.03, 0.03), mass=0.12):
    collision = p.createCollisionShape(
        p.GEOM_BOX,
        halfExtents=half_extents
    )
    visual = p.createVisualShape(
        p.GEOM_BOX,
        halfExtents=half_extents,
        rgbaColor=rgba
    )
    block_id = p.createMultiBody(
        baseMass=mass,
        baseCollisionShapeIndex=collision,
        baseVisualShapeIndex=visual,
        basePosition=position
    )
    return block_id

def attach_block_to_ee(robot_id, block_id):
    joints = get_revolute_joints(robot_id)
    ee_link = joints[-1]
    ee_state = p.getLinkState(robot_id, ee_link)
    ee_pos = ee_state[0]
    ee_orn = ee_state[1]

    p.resetBasePositionAndOrientation(block_id, ee_pos, ee_orn)

    cid = p.createConstraint(
        parentBodyUniqueId=robot_id,
        parentLinkIndex=ee_link,
        childBodyUniqueId=block_id,
        childLinkIndex=-1,
        jointType=p.JOINT_FIXED,
        jointAxis=[0, 0, 0],
        parentFramePosition=[0, 0, 0.08],
        childFramePosition=[0, 0, 0]
    )
    return cid

def release_block(cid):
    p.removeConstraint(cid)

def pick_and_place(robot_id, block_id, pick_pos, place_pos):
    above_pick  = [pick_pos[0],  pick_pos[1],  pick_pos[2]  + 0.30]
    grab_pick   = [pick_pos[0],  pick_pos[1],  pick_pos[2]  + 0.08]
    above_place = [place_pos[0], place_pos[1], place_pos[2] + 0.30]
    set_place   = [place_pos[0], place_pos[1], place_pos[2] + 0.08]

    move_ee(robot_id, above_pick,  steps=100, capture_every=4)
    move_ee(robot_id, grab_pick,   steps=90,  capture_every=4)

    cid = attach_block_to_ee(robot_id, block_id)
    capture_frame()

    move_ee(robot_id, above_pick,  steps=90,  capture_every=4)
    move_ee(robot_id, above_place, steps=120, capture_every=4)
    move_ee(robot_id, set_place,   steps=90,  capture_every=4)

    release_block(cid)
    step_and_capture(40, capture_every=2)

    move_ee(robot_id, above_place, steps=80, capture_every=4)

# ----------------------------
# Home pose
# ----------------------------
home_q = [0, 0.4, 0, -1.6, 0, 1.2, 0]
for robot_id in robots:
    reset_arm_pose(robot_id, home_q)

step_and_capture(60, capture_every=4)

# ----------------------------
# Create 3 platforms (one per robot)
# Each robot gets 3 cubes
# ----------------------------
platform_positions = [
    [-spacing, 1.18, 0.02],
    [0.0,      1.18, 0.02],
    [spacing,  1.18, 0.02],
]

for pos in platform_positions:
    platform_collision = p.createCollisionShape(
        p.GEOM_BOX,
        halfExtents=[0.11, 0.11, 0.02]
    )
    platform_visual = p.createVisualShape(
        p.GEOM_BOX,
        halfExtents=[0.11, 0.11, 0.02],
        rgbaColor=[0.35, 0.35, 0.35, 1]
    )
    p.createMultiBody(
        baseMass=0,
        baseCollisionShapeIndex=platform_collision,
        baseVisualShapeIndex=platform_visual,
        basePosition=pos
    )

# ----------------------------
# 9 cubes total: 3 per robot
# ----------------------------
colors = [
    [1, 0, 0, 1],   # red
    [1, 1, 1, 1],   # white
    [0, 0, 1, 1],   # blue
]

all_robot_blocks = []

for base_x, _, _ in robot_positions:
    cube_positions = [
        [base_x - 0.14, 0.76, 0.03],
        [base_x,        0.76, 0.03],
        [base_x + 0.14, 0.76, 0.03],
    ]
    robot_blocks = []
    for cube_pos, color in zip(cube_positions, colors):
        cube_id = create_colored_block(cube_pos, color)
        robot_blocks.append((cube_id, cube_pos))
    all_robot_blocks.append(robot_blocks)

step_and_capture(80, capture_every=4)

# ----------------------------
# Stack targets:
# each robot builds its own 3-cube stack
# ----------------------------
stack_targets = []
for plat_x, plat_y, _ in platform_positions:
    stack_targets.append([
        [plat_x, plat_y, 0.05],
        [plat_x, plat_y, 0.11],
        [plat_x, plat_y, 0.17],
    ])

# ----------------------------
# Run sequence
# Robot 1 stacks 3 cubes
# Robot 2 stacks 3 cubes
# Robot 3 stacks 3 cubes
# ----------------------------
for robot_idx in range(3):
    robot_id = robots[robot_idx]
    robot_blocks = all_robot_blocks[robot_idx]
    robot_stack_targets = stack_targets[robot_idx]

    for cube_idx in range(3):
        block_id, pick_pos = robot_blocks[cube_idx]
        place_pos = robot_stack_targets[cube_idx]
        pick_and_place(robot_id, block_id, pick_pos, place_pos)

step_and_capture(120, capture_every=3)

# ----------------------------
# Export video
# ----------------------------
video_path = "/content/three_robots_three_cubes_each.mp4"
imageio.mimsave(video_path, frames, fps=20)

Video(video_path, embed=True)